---

- hosts: all
  become: true

  tasks:

    - name: Install apache2 and php package for Ubuntu
      apt:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install apache and php package on CentOS
      vars:
        ansible_ssh_user: ec2-user
      dnf:
        name: 
          - httpd
          - php
        state: latest
        update_cache: true
      when: ansible_distribution == "RedHat"