---

- hosts: all
  become: true

  tasks:

    - name: Update repository index
      apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Install apache2 package
      apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Add php support for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Update repository index
      vars:
        ansible_ssh_user: ec2-user
      dnf:
        update_cache: true
      when: ansible_distribution == "CentOS"

    - name: Install apache2 package
      vars:
        ansible_ssh_user: ec2-user
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution == "CentOS"

    - name: Add php support for apache
      vars:
        ansible_ssh_user: ec2-user
      dnf:
        name: php
        state: latest
      when: ansible_distribution == "CentOS"