---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (RedHat)
      dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "RedHat"

    - name: Install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

    - name: Install apache2 and php package for Ubuntu servers
      apt:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install apache and php package on RedHat
      vars:
        ansible_ssh_user: ec2-user
      dnf:
        name: 
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

- hosts: db_servers
  become: true
  tasks:
    - name: Install mariadb package (RedHat)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "ReadHat"

    - name: Install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"


- hosts: file_servers
  become: true
  tasks:
    - name: Install samba package
      package:
        name: samba
        state: latest