- name: Install apache2 and php package for Ubuntu servers
  tags: apache,apache2,ubuntu
  apt:
    name: 
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install apache and php package on RedHat
  tags: apache,redhat,httpd
  vars:
    ansible_ssh_user: ec2-user
  dnf:
    name: 
      - httpd
      - php
    state: latest
  when: ansible_distribution == "RedHat"

- name: start httpd (RedHat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "RedHat"

- name: Change email address for admin
  tags: apache,redhat,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebodyhuey@somewhere.net
  when: ansible_distribution == "RedHat"
  register: httpd

- name: restart httpd (Redhat)
  tags: apache,redhat,httpd
  service:
    name: httpd
    state: restarted
  when: httpd.changed

- name: Copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: ../files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644